In [10]:
a[:,1]+2000

array([ 8012,  9012,  8886,  9250,  6598,  7564,  8971,  9763, 10032,
       11565])

In [9]:
a[:,1]

array([6012, 7012, 6886, 7250, 4598, 5564, 6971, 7763, 8032, 9565])

In [8]:
a[:,0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
a=np.array([[1,6012],[2,7012],[3,6886],[4,7250],[5,4598],[6,5564],[7,6971],[8,7763],[9,8032],[10,9565]])
print(np.array(a))

[[   1 6012]
 [   2 7012]
 [   3 6886]
 [   4 7250]
 [   5 4598]
 [   6 5564]
 [   7 6971]
 [   8 7763]
 [   9 8032]
 [  10 9565]]


In [1]:
import numpy as np

In [21]:
np.max(a)

np.int64(9565)

In [22]:
np.max(a[:,1])

np.int64(9565)

In [23]:
a[:,1]>7000

array([False,  True, False,  True, False, False, False,  True,  True,
        True])

In [24]:
[a[:,1]>7000]

[array([False,  True, False,  True, False, False, False,  True,  True,
         True])]